### ISSUE TITLE
Merge in outstanding pull requests for v2.5.0 release

### ISSUE THREAD

**Issue by jonbullock** [jbake-org/jbake#242]
I'm manually merging in the outstanding pull requests marked with v2.5.0 in a separate branch (merge-2-5-0-prs) at the moment and I've created this issue to track my progress and list the outstanding clean up tasks.

**Comment by jonbullock** [comment]
Pull requests to merge in:

- [x] #186 Pagination
- [x] #175 Simplify and aggregate rendering testing
- [x] #185 Introduced Groovy MarkupTemplateEngine
- [x] #161 Added support for Pebble template engine 
- [x] #166 Jade template engine implementation
- [x] #154 Support for Jade template engine
- [x] #135 Preliminary refactoring
- [x] #138 Extracted various rendering modes to allow their customisation
- [x] ~~#120 WIP: Rework commandline~~
- [ ] #104 Extensonless URLs

Clean up tasks so far:

- [ ] Merge FreemarkerRendererTest into abstract system and remove FreemarkerRendererTest
- [ ] Duplication of freemarker templates in tests (/templates & /freemarkerTemplates) needs to be solved
- [ ] Rename GroovyTemplateEngine class to GroovySimpleTemplateEngine class and associated tests (or should other name considering the engine uses Simple & Xml)
- [ ] Use static references to data model variable names in GroovyMarkupTemplateEngine & PebbleTemplateEngine
- [ ] Either merge RendererSpec.groovy into exiting Java unit tests or keep it and make sure there is no overlap between existing Java unit tests and this
- [ ] Move PebbleRendererTest class into /template package and update so matches other engine tests
- [ ] Deal with assembly-example-project-pebble.xml not linked up to relevant source (not used in pom.xml)
- [ ] Use static references to data model variable names in JadeTemplateEngine
- [ ] Deal with assembly-example-project-jade.xml not pointing to any files?
- [ ] Merge JadeRendererTest into abstract system
- [ ] Move JadeRendererTest class into /template package and update to matches other engine tests
- [ ] Arrange to move github.com/mariuszs/jbake-example-project-jade to JBake org
- [ ] Apply ModelExtractors to new template engines (Groovy Markup, Pebble and Jade)

**Comment by haumacher** [comment]
Don't you think that #219 "Detailed errors with stack trace of the original problem" isn't also a normative candidate for such a cleanup release?

A part of my wikibake experiments (#227) I've also introduced some additional abstractions around the document model handling. These refactorings have no influence to the application functionality, but the wikibaking heavily depends on it. If I had the chance of getting these refactorings integrated into a pending release, I could extract them to a separate PR to make the outstanding wikibake changes smaller.

**Comment by jonbullock** [comment]
Thanks for reminding me, I've scheduled #219 in for v2.5.0.

Please be aware there are some significant changes to the code in the pull requests above.

**Comment by jonbullock** [comment]
@haumacher could you direct me to the abstractions you're referring to?

**Comment by haumacher** [comment]
@jonbullock I primarily mean the encapsulation of the document properties that were represented as `Map<String,Object>` into a separate class `JDocument`. And additionally using Java constants for all these document properties that are scattered all over the code as String literals (see https://github.com/haumacher/jbake/commit/87d0072f78654cc83761cc2e8a5a3b4d69625c68).

But there are more refactorings done in https://github.com/haumacher/jbake/commits/wikibake.1?page=1

**Comment by jonbullock** [comment]
@haumacher I can see that being a benefit for future plans so if you're willing to extract that into a separate PR I'd be happy to include it. Most of those string literals have been dealt with as part of 2474ad93ff249ecbb8722e39fd102c8400090148 but they always felt out of place in Crawler so putting them into JDocument seems like the right place.

**Comment by jonbullock** [comment]
The PR's listed in this issue have now been merged and clean up tasks performed.
